# Конфигурация параметров для расчета диаметров многоствольных деревьев
# Раскомментируйте и настройте нужные параметры:

intensity_cut: 3000
height_threshold: 1.5
min_trunk_diameter: 5.0
max_trunk_distance: 2.0 