# Конфигурация параметров для расчета диаметров многоствольных деревьев

device: 'cuda'
find_trunk_ml:
  feature_params:
    illuminance:
      num_rays: 4
      max_ray_distance: 0.5
      ao_neighbor_radius: 0.02
  proba_threshold: 0.5
